/*
 *  api person
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baeldung.petstore.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PersonInput
 */
public class PersonInputTest {
    private final PersonInput model = new PersonInput();

    /**
     * Model tests for PersonInput
     */
    @Test
    public void testPersonInput() {
        // TODO: test PersonInput
    }

    /**
     * Test the property 'fname'
     */
    @Test
    public void fnameTest() {
        // TODO: test fname
    }

    /**
     * Test the property 'lname'
     */
    @Test
    public void lnameTest() {
        // TODO: test lname
    }

    /**
     * Test the property 'age'
     */
    @Test
    public void ageTest() {
        // TODO: test age
    }

}
