/*
 *  api person
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.baeldung.petstore.client.api;

import com.baeldung.petstore.client.invoker.*;
import com.baeldung.petstore.client.invoker.auth.*;
import com.baeldung.petstore.client.model.Person;
import com.baeldung.petstore.client.model.PersonInput;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void operation2DeleteIdTest() throws ApiException {
        //Integer id = null;
        //Object response = api.operation2DeleteId(id);
        // TODO: test validations
    }

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void operation2GetIdTest() throws ApiException {
        //Integer id = null;
        //Object response = api.operation2GetId(id);
        // TODO: test validations
    }

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void operation3GetTest() throws ApiException {
        //List<Object> response = api.operation3Get();
        // TODO: test validations
    }

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void operation3PostTest() throws ApiException {
        //PersonInput personInput = null;
        //Object response = api.operation3Post(personInput);
        // TODO: test validations
    }

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void operation3PutTest() throws ApiException {
        //Person person = null;
        //Object response = api.operation3Put(person);
        // TODO: test validations
    }

}
